#日志模块的配置文件
logging:
  config: src/main/resources/log4j2-prod.xml

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_prod?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: root
  redis:
    database: 1
    host: localhost
    port: 6379

#是否开启swagger，生产环境不开启
swagger:
  enable: false